// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

/*
Package service is a generated protocol buffer package.

It is generated from these files:
	service.proto

It has these top-level messages:
	Message
	ReqLogin
	ReqCreate
	ReqJoin
	ReqAction1
	ReqQuit
	ReqRoomList
	ResLogin
	ResCreate
	ResJoin
	ResAction1
	ResQuit
	ResRoomList
	NotifyJoinMsg
	NotifyAction1Msg
	NotifyQuitMsg
	ErrorMsg
*/
package service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message struct {
	UserID    int64 `protobuf:"varint,1,opt,name=userID" json:"userID,omitempty"`
	Timestamp int64 `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Payload:
	//	*Message_ReqLogin
	//	*Message_ReqCreate
	//	*Message_ReqJoin
	//	*Message_ReqAction1
	//	*Message_ReqQuit
	//	*Message_ReqRoomList
	//	*Message_ResLogin
	//	*Message_ResCreate
	//	*Message_ResJoin
	//	*Message_ResAction1
	//	*Message_ResQuit
	//	*Message_ResRoomList
	//	*Message_NotifyJoin
	//	*Message_NotifyAction1
	//	*Message_NotifyQuit
	//	*Message_Error
	Payload isMessage_Payload `protobuf_oneof:"payload"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isMessage_Payload interface {
	isMessage_Payload()
}

type Message_ReqLogin struct {
	ReqLogin *ReqLogin `protobuf:"bytes,3,opt,name=req_login,json=reqLogin,oneof"`
}
type Message_ReqCreate struct {
	ReqCreate *ReqCreate `protobuf:"bytes,4,opt,name=req_create,json=reqCreate,oneof"`
}
type Message_ReqJoin struct {
	ReqJoin *ReqJoin `protobuf:"bytes,5,opt,name=req_join,json=reqJoin,oneof"`
}
type Message_ReqAction1 struct {
	ReqAction1 *ReqAction1 `protobuf:"bytes,6,opt,name=req_action1,json=reqAction1,oneof"`
}
type Message_ReqQuit struct {
	ReqQuit *ReqQuit `protobuf:"bytes,7,opt,name=req_quit,json=reqQuit,oneof"`
}
type Message_ReqRoomList struct {
	ReqRoomList *ReqRoomList `protobuf:"bytes,8,opt,name=req_room_list,json=reqRoomList,oneof"`
}
type Message_ResLogin struct {
	ResLogin *ResLogin `protobuf:"bytes,9,opt,name=res_login,json=resLogin,oneof"`
}
type Message_ResCreate struct {
	ResCreate *ResCreate `protobuf:"bytes,10,opt,name=res_create,json=resCreate,oneof"`
}
type Message_ResJoin struct {
	ResJoin *ResJoin `protobuf:"bytes,11,opt,name=res_join,json=resJoin,oneof"`
}
type Message_ResAction1 struct {
	ResAction1 *ResAction1 `protobuf:"bytes,12,opt,name=res_action1,json=resAction1,oneof"`
}
type Message_ResQuit struct {
	ResQuit *ResQuit `protobuf:"bytes,13,opt,name=res_quit,json=resQuit,oneof"`
}
type Message_ResRoomList struct {
	ResRoomList *ResRoomList `protobuf:"bytes,14,opt,name=res_room_list,json=resRoomList,oneof"`
}
type Message_NotifyJoin struct {
	NotifyJoin *NotifyJoinMsg `protobuf:"bytes,15,opt,name=notify_join,json=notifyJoin,oneof"`
}
type Message_NotifyAction1 struct {
	NotifyAction1 *NotifyAction1Msg `protobuf:"bytes,16,opt,name=notify_action1,json=notifyAction1,oneof"`
}
type Message_NotifyQuit struct {
	NotifyQuit *NotifyQuitMsg `protobuf:"bytes,17,opt,name=notify_quit,json=notifyQuit,oneof"`
}
type Message_Error struct {
	Error *ErrorMsg `protobuf:"bytes,1000,opt,name=error,oneof"`
}

func (*Message_ReqLogin) isMessage_Payload()      {}
func (*Message_ReqCreate) isMessage_Payload()     {}
func (*Message_ReqJoin) isMessage_Payload()       {}
func (*Message_ReqAction1) isMessage_Payload()    {}
func (*Message_ReqQuit) isMessage_Payload()       {}
func (*Message_ReqRoomList) isMessage_Payload()   {}
func (*Message_ResLogin) isMessage_Payload()      {}
func (*Message_ResCreate) isMessage_Payload()     {}
func (*Message_ResJoin) isMessage_Payload()       {}
func (*Message_ResAction1) isMessage_Payload()    {}
func (*Message_ResQuit) isMessage_Payload()       {}
func (*Message_ResRoomList) isMessage_Payload()   {}
func (*Message_NotifyJoin) isMessage_Payload()    {}
func (*Message_NotifyAction1) isMessage_Payload() {}
func (*Message_NotifyQuit) isMessage_Payload()    {}
func (*Message_Error) isMessage_Payload()         {}

func (m *Message) GetPayload() isMessage_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Message) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *Message) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Message) GetReqLogin() *ReqLogin {
	if x, ok := m.GetPayload().(*Message_ReqLogin); ok {
		return x.ReqLogin
	}
	return nil
}

func (m *Message) GetReqCreate() *ReqCreate {
	if x, ok := m.GetPayload().(*Message_ReqCreate); ok {
		return x.ReqCreate
	}
	return nil
}

func (m *Message) GetReqJoin() *ReqJoin {
	if x, ok := m.GetPayload().(*Message_ReqJoin); ok {
		return x.ReqJoin
	}
	return nil
}

func (m *Message) GetReqAction1() *ReqAction1 {
	if x, ok := m.GetPayload().(*Message_ReqAction1); ok {
		return x.ReqAction1
	}
	return nil
}

func (m *Message) GetReqQuit() *ReqQuit {
	if x, ok := m.GetPayload().(*Message_ReqQuit); ok {
		return x.ReqQuit
	}
	return nil
}

func (m *Message) GetReqRoomList() *ReqRoomList {
	if x, ok := m.GetPayload().(*Message_ReqRoomList); ok {
		return x.ReqRoomList
	}
	return nil
}

func (m *Message) GetResLogin() *ResLogin {
	if x, ok := m.GetPayload().(*Message_ResLogin); ok {
		return x.ResLogin
	}
	return nil
}

func (m *Message) GetResCreate() *ResCreate {
	if x, ok := m.GetPayload().(*Message_ResCreate); ok {
		return x.ResCreate
	}
	return nil
}

func (m *Message) GetResJoin() *ResJoin {
	if x, ok := m.GetPayload().(*Message_ResJoin); ok {
		return x.ResJoin
	}
	return nil
}

func (m *Message) GetResAction1() *ResAction1 {
	if x, ok := m.GetPayload().(*Message_ResAction1); ok {
		return x.ResAction1
	}
	return nil
}

func (m *Message) GetResQuit() *ResQuit {
	if x, ok := m.GetPayload().(*Message_ResQuit); ok {
		return x.ResQuit
	}
	return nil
}

func (m *Message) GetResRoomList() *ResRoomList {
	if x, ok := m.GetPayload().(*Message_ResRoomList); ok {
		return x.ResRoomList
	}
	return nil
}

func (m *Message) GetNotifyJoin() *NotifyJoinMsg {
	if x, ok := m.GetPayload().(*Message_NotifyJoin); ok {
		return x.NotifyJoin
	}
	return nil
}

func (m *Message) GetNotifyAction1() *NotifyAction1Msg {
	if x, ok := m.GetPayload().(*Message_NotifyAction1); ok {
		return x.NotifyAction1
	}
	return nil
}

func (m *Message) GetNotifyQuit() *NotifyQuitMsg {
	if x, ok := m.GetPayload().(*Message_NotifyQuit); ok {
		return x.NotifyQuit
	}
	return nil
}

func (m *Message) GetError() *ErrorMsg {
	if x, ok := m.GetPayload().(*Message_Error); ok {
		return x.Error
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Message) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Message_OneofMarshaler, _Message_OneofUnmarshaler, _Message_OneofSizer, []interface{}{
		(*Message_ReqLogin)(nil),
		(*Message_ReqCreate)(nil),
		(*Message_ReqJoin)(nil),
		(*Message_ReqAction1)(nil),
		(*Message_ReqQuit)(nil),
		(*Message_ReqRoomList)(nil),
		(*Message_ResLogin)(nil),
		(*Message_ResCreate)(nil),
		(*Message_ResJoin)(nil),
		(*Message_ResAction1)(nil),
		(*Message_ResQuit)(nil),
		(*Message_ResRoomList)(nil),
		(*Message_NotifyJoin)(nil),
		(*Message_NotifyAction1)(nil),
		(*Message_NotifyQuit)(nil),
		(*Message_Error)(nil),
	}
}

func _Message_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Message)
	// payload
	switch x := m.Payload.(type) {
	case *Message_ReqLogin:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ReqLogin); err != nil {
			return err
		}
	case *Message_ReqCreate:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ReqCreate); err != nil {
			return err
		}
	case *Message_ReqJoin:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ReqJoin); err != nil {
			return err
		}
	case *Message_ReqAction1:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ReqAction1); err != nil {
			return err
		}
	case *Message_ReqQuit:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ReqQuit); err != nil {
			return err
		}
	case *Message_ReqRoomList:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ReqRoomList); err != nil {
			return err
		}
	case *Message_ResLogin:
		b.EncodeVarint(9<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ResLogin); err != nil {
			return err
		}
	case *Message_ResCreate:
		b.EncodeVarint(10<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ResCreate); err != nil {
			return err
		}
	case *Message_ResJoin:
		b.EncodeVarint(11<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ResJoin); err != nil {
			return err
		}
	case *Message_ResAction1:
		b.EncodeVarint(12<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ResAction1); err != nil {
			return err
		}
	case *Message_ResQuit:
		b.EncodeVarint(13<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ResQuit); err != nil {
			return err
		}
	case *Message_ResRoomList:
		b.EncodeVarint(14<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ResRoomList); err != nil {
			return err
		}
	case *Message_NotifyJoin:
		b.EncodeVarint(15<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.NotifyJoin); err != nil {
			return err
		}
	case *Message_NotifyAction1:
		b.EncodeVarint(16<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.NotifyAction1); err != nil {
			return err
		}
	case *Message_NotifyQuit:
		b.EncodeVarint(17<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.NotifyQuit); err != nil {
			return err
		}
	case *Message_Error:
		b.EncodeVarint(1000<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Error); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Message.Payload has unexpected type %T", x)
	}
	return nil
}

func _Message_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Message)
	switch tag {
	case 3: // payload.req_login
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ReqLogin)
		err := b.DecodeMessage(msg)
		m.Payload = &Message_ReqLogin{msg}
		return true, err
	case 4: // payload.req_create
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ReqCreate)
		err := b.DecodeMessage(msg)
		m.Payload = &Message_ReqCreate{msg}
		return true, err
	case 5: // payload.req_join
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ReqJoin)
		err := b.DecodeMessage(msg)
		m.Payload = &Message_ReqJoin{msg}
		return true, err
	case 6: // payload.req_action1
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ReqAction1)
		err := b.DecodeMessage(msg)
		m.Payload = &Message_ReqAction1{msg}
		return true, err
	case 7: // payload.req_quit
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ReqQuit)
		err := b.DecodeMessage(msg)
		m.Payload = &Message_ReqQuit{msg}
		return true, err
	case 8: // payload.req_room_list
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ReqRoomList)
		err := b.DecodeMessage(msg)
		m.Payload = &Message_ReqRoomList{msg}
		return true, err
	case 9: // payload.res_login
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ResLogin)
		err := b.DecodeMessage(msg)
		m.Payload = &Message_ResLogin{msg}
		return true, err
	case 10: // payload.res_create
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ResCreate)
		err := b.DecodeMessage(msg)
		m.Payload = &Message_ResCreate{msg}
		return true, err
	case 11: // payload.res_join
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ResJoin)
		err := b.DecodeMessage(msg)
		m.Payload = &Message_ResJoin{msg}
		return true, err
	case 12: // payload.res_action1
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ResAction1)
		err := b.DecodeMessage(msg)
		m.Payload = &Message_ResAction1{msg}
		return true, err
	case 13: // payload.res_quit
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ResQuit)
		err := b.DecodeMessage(msg)
		m.Payload = &Message_ResQuit{msg}
		return true, err
	case 14: // payload.res_room_list
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ResRoomList)
		err := b.DecodeMessage(msg)
		m.Payload = &Message_ResRoomList{msg}
		return true, err
	case 15: // payload.notify_join
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(NotifyJoinMsg)
		err := b.DecodeMessage(msg)
		m.Payload = &Message_NotifyJoin{msg}
		return true, err
	case 16: // payload.notify_action1
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(NotifyAction1Msg)
		err := b.DecodeMessage(msg)
		m.Payload = &Message_NotifyAction1{msg}
		return true, err
	case 17: // payload.notify_quit
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(NotifyQuitMsg)
		err := b.DecodeMessage(msg)
		m.Payload = &Message_NotifyQuit{msg}
		return true, err
	case 1000: // payload.error
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ErrorMsg)
		err := b.DecodeMessage(msg)
		m.Payload = &Message_Error{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Message_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Message)
	// payload
	switch x := m.Payload.(type) {
	case *Message_ReqLogin:
		s := proto.Size(x.ReqLogin)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_ReqCreate:
		s := proto.Size(x.ReqCreate)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_ReqJoin:
		s := proto.Size(x.ReqJoin)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_ReqAction1:
		s := proto.Size(x.ReqAction1)
		n += proto.SizeVarint(6<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_ReqQuit:
		s := proto.Size(x.ReqQuit)
		n += proto.SizeVarint(7<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_ReqRoomList:
		s := proto.Size(x.ReqRoomList)
		n += proto.SizeVarint(8<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_ResLogin:
		s := proto.Size(x.ResLogin)
		n += proto.SizeVarint(9<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_ResCreate:
		s := proto.Size(x.ResCreate)
		n += proto.SizeVarint(10<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_ResJoin:
		s := proto.Size(x.ResJoin)
		n += proto.SizeVarint(11<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_ResAction1:
		s := proto.Size(x.ResAction1)
		n += proto.SizeVarint(12<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_ResQuit:
		s := proto.Size(x.ResQuit)
		n += proto.SizeVarint(13<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_ResRoomList:
		s := proto.Size(x.ResRoomList)
		n += proto.SizeVarint(14<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_NotifyJoin:
		s := proto.Size(x.NotifyJoin)
		n += proto.SizeVarint(15<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_NotifyAction1:
		s := proto.Size(x.NotifyAction1)
		n += proto.SizeVarint(16<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_NotifyQuit:
		s := proto.Size(x.NotifyQuit)
		n += proto.SizeVarint(17<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_Error:
		s := proto.Size(x.Error)
		n += proto.SizeVarint(1000<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// request payload
type ReqLogin struct {
}

func (m *ReqLogin) Reset()                    { *m = ReqLogin{} }
func (m *ReqLogin) String() string            { return proto.CompactTextString(m) }
func (*ReqLogin) ProtoMessage()               {}
func (*ReqLogin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ReqCreate struct {
}

func (m *ReqCreate) Reset()                    { *m = ReqCreate{} }
func (m *ReqCreate) String() string            { return proto.CompactTextString(m) }
func (*ReqCreate) ProtoMessage()               {}
func (*ReqCreate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ReqJoin struct {
	RoomID int64 `protobuf:"varint,1,opt,name=roomID" json:"roomID,omitempty"`
}

func (m *ReqJoin) Reset()                    { *m = ReqJoin{} }
func (m *ReqJoin) String() string            { return proto.CompactTextString(m) }
func (*ReqJoin) ProtoMessage()               {}
func (*ReqJoin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReqJoin) GetRoomID() int64 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

type ReqAction1 struct {
}

func (m *ReqAction1) Reset()                    { *m = ReqAction1{} }
func (m *ReqAction1) String() string            { return proto.CompactTextString(m) }
func (*ReqAction1) ProtoMessage()               {}
func (*ReqAction1) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type ReqQuit struct {
}

func (m *ReqQuit) Reset()                    { *m = ReqQuit{} }
func (m *ReqQuit) String() string            { return proto.CompactTextString(m) }
func (*ReqQuit) ProtoMessage()               {}
func (*ReqQuit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type ReqRoomList struct {
}

func (m *ReqRoomList) Reset()                    { *m = ReqRoomList{} }
func (m *ReqRoomList) String() string            { return proto.CompactTextString(m) }
func (*ReqRoomList) ProtoMessage()               {}
func (*ReqRoomList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

// response payload
type ResLogin struct {
	Result int32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
}

func (m *ResLogin) Reset()                    { *m = ResLogin{} }
func (m *ResLogin) String() string            { return proto.CompactTextString(m) }
func (*ResLogin) ProtoMessage()               {}
func (*ResLogin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ResLogin) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type ResCreate struct {
	RoomID int64 `protobuf:"varint,1,opt,name=roomID" json:"roomID,omitempty"`
}

func (m *ResCreate) Reset()                    { *m = ResCreate{} }
func (m *ResCreate) String() string            { return proto.CompactTextString(m) }
func (*ResCreate) ProtoMessage()               {}
func (*ResCreate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ResCreate) GetRoomID() int64 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

type ResJoin struct {
	RoomID  int64   `protobuf:"varint,1,opt,name=roomID" json:"roomID,omitempty"`
	Members []int64 `protobuf:"varint,2,rep,packed,name=members" json:"members,omitempty"`
}

func (m *ResJoin) Reset()                    { *m = ResJoin{} }
func (m *ResJoin) String() string            { return proto.CompactTextString(m) }
func (*ResJoin) ProtoMessage()               {}
func (*ResJoin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ResJoin) GetRoomID() int64 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *ResJoin) GetMembers() []int64 {
	if m != nil {
		return m.Members
	}
	return nil
}

type ResAction1 struct {
	Result int32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
}

func (m *ResAction1) Reset()                    { *m = ResAction1{} }
func (m *ResAction1) String() string            { return proto.CompactTextString(m) }
func (*ResAction1) ProtoMessage()               {}
func (*ResAction1) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *ResAction1) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type ResQuit struct {
	IsSuccess int32 `protobuf:"varint,1,opt,name=isSuccess" json:"isSuccess,omitempty"`
}

func (m *ResQuit) Reset()                    { *m = ResQuit{} }
func (m *ResQuit) String() string            { return proto.CompactTextString(m) }
func (*ResQuit) ProtoMessage()               {}
func (*ResQuit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *ResQuit) GetIsSuccess() int32 {
	if m != nil {
		return m.IsSuccess
	}
	return 0
}

type ResRoomList struct {
	RoomIDs []int64 `protobuf:"varint,1,rep,packed,name=roomIDs" json:"roomIDs,omitempty"`
}

func (m *ResRoomList) Reset()                    { *m = ResRoomList{} }
func (m *ResRoomList) String() string            { return proto.CompactTextString(m) }
func (*ResRoomList) ProtoMessage()               {}
func (*ResRoomList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *ResRoomList) GetRoomIDs() []int64 {
	if m != nil {
		return m.RoomIDs
	}
	return nil
}

// notify message type (for client)
type NotifyJoinMsg struct {
	RoomID int64 `protobuf:"varint,1,opt,name=roomID" json:"roomID,omitempty"`
}

func (m *NotifyJoinMsg) Reset()                    { *m = NotifyJoinMsg{} }
func (m *NotifyJoinMsg) String() string            { return proto.CompactTextString(m) }
func (*NotifyJoinMsg) ProtoMessage()               {}
func (*NotifyJoinMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *NotifyJoinMsg) GetRoomID() int64 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

type NotifyAction1Msg struct {
}

func (m *NotifyAction1Msg) Reset()                    { *m = NotifyAction1Msg{} }
func (m *NotifyAction1Msg) String() string            { return proto.CompactTextString(m) }
func (*NotifyAction1Msg) ProtoMessage()               {}
func (*NotifyAction1Msg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

type NotifyQuitMsg struct {
	RoomID int64 `protobuf:"varint,1,opt,name=roomID" json:"roomID,omitempty"`
}

func (m *NotifyQuitMsg) Reset()                    { *m = NotifyQuitMsg{} }
func (m *NotifyQuitMsg) String() string            { return proto.CompactTextString(m) }
func (*NotifyQuitMsg) ProtoMessage()               {}
func (*NotifyQuitMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *NotifyQuitMsg) GetRoomID() int64 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

// error message
type ErrorMsg struct {
	ErrCode    int32  `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
	ErrMessage string `protobuf:"bytes,2,opt,name=errMessage" json:"errMessage,omitempty"`
}

func (m *ErrorMsg) Reset()                    { *m = ErrorMsg{} }
func (m *ErrorMsg) String() string            { return proto.CompactTextString(m) }
func (*ErrorMsg) ProtoMessage()               {}
func (*ErrorMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *ErrorMsg) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *ErrorMsg) GetErrMessage() string {
	if m != nil {
		return m.ErrMessage
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "service.Message")
	proto.RegisterType((*ReqLogin)(nil), "service.ReqLogin")
	proto.RegisterType((*ReqCreate)(nil), "service.ReqCreate")
	proto.RegisterType((*ReqJoin)(nil), "service.ReqJoin")
	proto.RegisterType((*ReqAction1)(nil), "service.ReqAction1")
	proto.RegisterType((*ReqQuit)(nil), "service.ReqQuit")
	proto.RegisterType((*ReqRoomList)(nil), "service.ReqRoomList")
	proto.RegisterType((*ResLogin)(nil), "service.ResLogin")
	proto.RegisterType((*ResCreate)(nil), "service.ResCreate")
	proto.RegisterType((*ResJoin)(nil), "service.ResJoin")
	proto.RegisterType((*ResAction1)(nil), "service.ResAction1")
	proto.RegisterType((*ResQuit)(nil), "service.ResQuit")
	proto.RegisterType((*ResRoomList)(nil), "service.ResRoomList")
	proto.RegisterType((*NotifyJoinMsg)(nil), "service.NotifyJoinMsg")
	proto.RegisterType((*NotifyAction1Msg)(nil), "service.NotifyAction1Msg")
	proto.RegisterType((*NotifyQuitMsg)(nil), "service.NotifyQuitMsg")
	proto.RegisterType((*ErrorMsg)(nil), "service.ErrorMsg")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Gateway service

type GatewayClient interface {
	RouteMessage(ctx context.Context, opts ...grpc.CallOption) (Gateway_RouteMessageClient, error)
}

type gatewayClient struct {
	cc *grpc.ClientConn
}

func NewGatewayClient(cc *grpc.ClientConn) GatewayClient {
	return &gatewayClient{cc}
}

func (c *gatewayClient) RouteMessage(ctx context.Context, opts ...grpc.CallOption) (Gateway_RouteMessageClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Gateway_serviceDesc.Streams[0], c.cc, "/service.Gateway/RouteMessage", opts...)
	if err != nil {
		return nil, err
	}
	x := &gatewayRouteMessageClient{stream}
	return x, nil
}

type Gateway_RouteMessageClient interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ClientStream
}

type gatewayRouteMessageClient struct {
	grpc.ClientStream
}

func (x *gatewayRouteMessageClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gatewayRouteMessageClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Gateway service

type GatewayServer interface {
	RouteMessage(Gateway_RouteMessageServer) error
}

func RegisterGatewayServer(s *grpc.Server, srv GatewayServer) {
	s.RegisterService(&_Gateway_serviceDesc, srv)
}

func _Gateway_RouteMessage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GatewayServer).RouteMessage(&gatewayRouteMessageServer{stream})
}

type Gateway_RouteMessageServer interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type gatewayRouteMessageServer struct {
	grpc.ServerStream
}

func (x *gatewayRouteMessageServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gatewayRouteMessageServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Gateway_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.Gateway",
	HandlerType: (*GatewayServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RouteMessage",
			Handler:       _Gateway_RouteMessage_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "service.proto",
}

func init() { proto.RegisterFile("service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 627 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x95, 0x6f, 0x4f, 0xd4, 0x4e,
	0x10, 0xc7, 0xef, 0xb8, 0x1f, 0xf4, 0x3a, 0xa5, 0xfc, 0x60, 0x35, 0x64, 0x35, 0xc4, 0xe0, 0x6a,
	0xc2, 0xc5, 0x44, 0x82, 0x90, 0x18, 0xff, 0x3c, 0x12, 0x30, 0xa2, 0x01, 0x13, 0xeb, 0x0b, 0x20,
	0xe5, 0x58, 0x49, 0xcd, 0xb5, 0x0b, 0x3b, 0x5b, 0x0d, 0x6f, 0xc7, 0x57, 0xe7, 0xcb, 0x30, 0xb3,
	0xbb, 0x6d, 0xf7, 0xa8, 0xe7, 0xb3, 0xce, 0xec, 0x7e, 0xf7, 0x3b, 0xf3, 0xe9, 0x6c, 0x0b, 0x29,
	0x4a, 0xfd, 0xa3, 0x98, 0xca, 0xdd, 0x6b, 0xad, 0x8c, 0x62, 0x91, 0x0f, 0xc5, 0xaf, 0x08, 0xa2,
	0x33, 0x89, 0x98, 0x5f, 0x49, 0xb6, 0x09, 0x2b, 0x35, 0x4a, 0xfd, 0xf1, 0x98, 0x0f, 0xb7, 0x87,
	0x93, 0x51, 0xe6, 0x23, 0xb6, 0x05, 0xb1, 0x29, 0x4a, 0x89, 0x26, 0x2f, 0xaf, 0xf9, 0x92, 0x5d,
	0xea, 0x12, 0x6c, 0x0f, 0x62, 0x2d, 0x6f, 0xce, 0x67, 0xea, 0xaa, 0xa8, 0xf8, 0x68, 0x7b, 0x38,
	0x49, 0xf6, 0x37, 0x76, 0x1b, 0xb7, 0x4c, 0xde, 0x9c, 0xd2, 0xc2, 0xc9, 0x20, 0x1b, 0x6b, 0xff,
	0xcc, 0x0e, 0x00, 0x48, 0x31, 0xd5, 0x32, 0x37, 0x92, 0xff, 0x67, 0x25, 0x2c, 0x94, 0x1c, 0xd9,
	0x95, 0x93, 0x41, 0x46, 0x27, 0xbb, 0x80, 0x3d, 0x07, 0x3a, 0xe0, 0xfc, 0xbb, 0x2a, 0x2a, 0xbe,
	0x6c, 0x25, 0xeb, 0xa1, 0xe4, 0x93, 0xb2, 0x26, 0x91, 0x76, 0x8f, 0xec, 0x25, 0x24, 0xb4, 0x3d,
	0x9f, 0x9a, 0x42, 0x55, 0x2f, 0xf8, 0x8a, 0x55, 0xdc, 0x0b, 0x15, 0xef, 0xdc, 0xd2, 0xc9, 0x20,
	0xa3, 0x6a, 0x7c, 0xd4, 0xd8, 0xdc, 0xd4, 0x85, 0xe1, 0x51, 0xdf, 0xe6, 0x4b, 0x5d, 0x18, 0x6f,
	0x43, 0x8f, 0xec, 0x0d, 0xa4, 0xb4, 0x5d, 0x2b, 0x55, 0x9e, 0xcf, 0x0a, 0x34, 0x7c, 0x6c, 0x35,
	0xf7, 0x43, 0x4d, 0xa6, 0x54, 0x79, 0x5a, 0x20, 0xe9, 0xa8, 0xa6, 0x26, 0x74, 0xe0, 0xd0, 0x83,
	0x8b, 0x7b, 0xe0, 0x30, 0x00, 0x87, 0x01, 0x38, 0x6c, 0xc0, 0x41, 0x0f, 0x1c, 0x86, 0xe0, 0x30,
	0x04, 0x87, 0x0e, 0x5c, 0xd2, 0xeb, 0x08, 0x3b, 0x70, 0xd8, 0x81, 0xc3, 0x16, 0xdc, 0x6a, 0x0f,
	0x1c, 0xce, 0x81, 0xc3, 0x39, 0x70, 0xe8, 0xc0, 0xa5, 0x7d, 0x9b, 0x0e, 0x1c, 0x76, 0xe0, 0x30,
	0x00, 0xb7, 0xd6, 0x03, 0x87, 0xf3, 0xe0, 0xda, 0x90, 0xbd, 0x86, 0xa4, 0x52, 0xa6, 0xf8, 0x76,
	0xeb, 0x9a, 0xfa, 0xdf, 0x2a, 0x37, 0x5b, 0xe5, 0x67, 0xbb, 0x46, 0xcd, 0x9c, 0xe1, 0x15, 0x55,
	0x59, 0xb5, 0x09, 0x76, 0x08, 0x6b, 0x5e, 0xda, 0x34, 0xb8, 0x6e, 0xd5, 0x0f, 0xee, 0xa8, 0x7d,
	0x57, 0xee, 0x80, 0xb4, 0x0a, 0x73, 0x81, 0xbd, 0x6d, 0x76, 0xe3, 0xaf, 0xf6, 0xd4, 0xe4, 0x9c,
	0xbd, 0xed, 0xfa, 0x19, 0x2c, 0x4b, 0xad, 0x95, 0xe6, 0xbf, 0xa3, 0x3b, 0xef, 0xfb, 0x3d, 0xa5,
	0x9d, 0xc0, 0x6d, 0x39, 0x8c, 0x21, 0xba, 0xce, 0x6f, 0x67, 0x2a, 0xbf, 0x14, 0x00, 0xe3, 0xe6,
	0x22, 0x89, 0x04, 0xe2, 0xf6, 0x86, 0x88, 0xc7, 0x10, 0xf9, 0xd9, 0xa7, 0xcb, 0x4b, 0x30, 0xbb,
	0xcb, 0xeb, 0x22, 0xb1, 0x0a, 0xd0, 0x0d, 0xbb, 0x88, 0xad, 0x80, 0x6a, 0x11, 0x29, 0x24, 0xc1,
	0x70, 0x0a, 0x41, 0x1e, 0x7e, 0xce, 0xe8, 0x2c, 0x89, 0xf5, 0xcc, 0xd8, 0xb3, 0x96, 0x33, 0x1f,
	0x89, 0x27, 0xe4, 0xdd, 0xcc, 0xd5, 0x22, 0xc3, 0xb7, 0x64, 0x81, 0xff, 0xaa, 0x89, 0x71, 0x88,
	0x4a, 0x59, 0x5e, 0x48, 0x8d, 0x7c, 0x69, 0x7b, 0x34, 0x19, 0x65, 0x4d, 0x28, 0x9e, 0x52, 0xb5,
	0xed, 0x4c, 0x2d, 0xaa, 0x63, 0xc7, 0x5a, 0x58, 0xa2, 0x5b, 0x10, 0x17, 0xf8, 0xb5, 0x9e, 0x4e,
	0x25, 0xa2, 0xdf, 0xd5, 0x25, 0xc4, 0x0e, 0xf5, 0xd8, 0x0d, 0x0e, 0x87, 0xc8, 0x55, 0x40, 0x5b,
	0xad, 0xaf, 0x0f, 0xc5, 0x0e, 0xa4, 0x73, 0x63, 0xb3, 0xb0, 0x3b, 0x06, 0xeb, 0x77, 0x27, 0xa4,
	0x13, 0xfb, 0x97, 0xbe, 0x50, 0x7c, 0x0c, 0xe3, 0xe6, 0x3d, 0x53, 0x2d, 0x52, 0xeb, 0x23, 0x75,
	0x29, 0x7d, 0xd9, 0x4d, 0xc8, 0x1e, 0x01, 0x48, 0xad, 0xfd, 0x47, 0xd9, 0x7e, 0x6f, 0xe3, 0x2c,
	0xc8, 0xec, 0x1f, 0x41, 0xf4, 0x21, 0x37, 0xf2, 0x67, 0x7e, 0xcb, 0x5e, 0xc1, 0x6a, 0xa6, 0x6a,
	0x23, 0x9b, 0x2f, 0x78, 0x77, 0xe5, 0x7c, 0xe6, 0x61, 0x2f, 0x23, 0x06, 0x93, 0xe1, 0xde, 0xf0,
	0x62, 0xc5, 0xfe, 0x07, 0x0e, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0xe2, 0xbf, 0x80, 0x1e, 0x18,
	0x06, 0x00, 0x00,
}
